In [1]:
# xarray is required to run the utils import line
import xarray as xr
import glob

In [2]:
# import libraries & data pre-processing functions from utils.py
from utils import *

In [3]:
# Request an additional 10 cores of power for processing from the server
client = get_cluster("UCSB0021", cores = 40)

In [4]:
# apply peer2peer network communication across multiple devices
client.cluster

PBSCluster(ee98530c, 'tcp://128.117.208.111:46673', workers=0, threads=0, memory=0 B)

In [5]:
#-----------------------------------------------------
#---------Turn Params into Numpy array----------------
#-----------------------------------------------------
# Create an empty list to store the columns
columns = []

# Iterate over each data variable
for var_name in params.data_vars:
    # Extract the values for the current variable
    var_values = params[var_name].values
    # Stack the values into a single column
    stacked_values = var_values.ravel()
    # Append the stacked column to the list of columns
    columns.append(stacked_values)

# Stack all columns horizontally to create the final numpy data array
numpy_params = np.column_stack(columns)

numpy_params.shape

(500, 32)

In [6]:
print(numpy_params)

[[0.77831114 0.35802577 0.25502127 ... 0.39361723 0.07896155 0.68458797]
 [0.31932864 0.54880317 0.63019079 ... 0.04108439 0.27561916 0.87845469]
 [0.87677181 0.21079367 0.6621252  ... 0.81974643 0.84014328 0.95191497]
 ...
 [0.18596905 0.996422   0.42220946 ... 0.24264258 0.84227481 0.7311443 ]
 [0.26212961 0.9122803  0.5339336  ... 0.71595008 0.35301486 0.3580522 ]
 [0.42211367 0.83921159 0.14434242 ... 0.21237027 0.36344002 0.1567103 ]]


In [7]:
params

<xarray.Dataset> Size: 132kB
Dimensions:              (member: 500)
Coordinates:
  * member               (member) object 4kB 'LHC0001' 'LHC0002' ... 'LHC0500'
Data variables: (12/32)
    FUN_fracfixers       (member) float64 4kB 0.7783 0.3193 ... 0.2621 0.4221
    KCN                  (member) float64 4kB 0.358 0.5488 ... 0.9123 0.8392
    a_fix                (member) float64 4kB 0.255 0.6302 ... 0.5339 0.1443
    crit_dayl            (member) float64 4kB 0.4012 0.27 ... 0.9974 0.6571
    d_max                (member) float64 4kB 0.7978 0.5361 ... 0.9076 0.4009
    fff                  (member) float64 4kB 0.1301 0.6792 ... 0.9918 0.02798
    ...                   ...
    stem_leaf            (member) float64 4kB 0.1138 0.1273 ... 0.3328 0.347
    sucsat_sf            (member) float64 4kB 0.7982 0.3947 ... 0.3526 0.6515
    theta_cj             (member) float64 4kB 0.03646 0.09374 ... 0.8429 0.5055
    tpu25ratio           (member) float64 4kB 0.3936 0.04108 ... 0.716 0.2124
    tpuse_sf             (member) float64 4kB 0.07896 0.2756 ... 0.353 0.3634
    wc2wjb0              (member) float64 4kB 0.6846 0.8785 ... 0.3581 0.1567